#!/bin/sh

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-0 -d VI VII VIII IX X

# bspc config remove_disabled_monitors 	false
# bspc config remove_unplugged_monitors	false
# bspc config merge_overlapping_monitors 	false


# bspc config status_prefix       "$(hostnamectl --static)"
bspc config split_ratio         0.65

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  tru
bspc config single_monocle       false
bspc config center_pseudo_tiled  false

bspc config border_width        4
bspc config window_gap          2
bspc config split_ratio 		0.65
bspc config top_padding			6
bspc config right_padding       6
bspc config bottom_padding      6
bspc config left_padding        6


bspc config ignore_ewmh_focus false
       
       
#bspc config initial_polarity        first_child
bspc config history_aware_focus		false
bspc config focus_by_distance 		false
bspc config focus_follows_pointer	false
bspc config pointer_follows_focus 	false
bspc config pointer_follows_monitor false


#bspc config external_rules_command CMD

 

bspc config focused_border_color "#00EEEE"
bspc config normal_border_color "#1874CD"
bspc config presel_feedback_color "#1E90FF"
bspc config active_border_color   "#008B8B"

# SELECTOR = (<class_name>|*)[:(<instance_name>|*)
# node=NODE_SEL[state=STATE] [layer=LAYER [split_dir=DIR] [split_ratio=RATIO] 
# (locked|sticky|private|center|follow|manage|focus|border)=(on|off)
# 
# States
# tiled
#    Its size and position are determined by the splitting type and ratio of each node of its path in the window tree.
# pseudo_tiled
#    Has an unrestricted size while being centered in its tiling space.
# floating
#    Can be moved/resized freely. Although it doesn’t occupy any tiling space, it is still part of the window tree.
# fullscreen
#    Fills its monitor rectangle and has no borders. It is send in the ABOVE layer by default.
# 
# Flags
# locked
#    Ignores the node --close message.
# sticky
#    Stays in the focused desktop of its monitor.
# private
#    Tries to keep the same tiling position/size.
# urgent
#    Has its urgency hint set. This flag is set externally.


bspc rule  -a *:bashrun state=floating follow=on private=on manage=off layer=above
bspc rule  -a qarma state=floating follow=on private=on layer=above
#bspc rule -a Gimp desktop=^2 floating=on
bspc rule -a Gimp  state=fullscreen
bspc rule -a Chromium state=fullscreen
bspc rule  -a tint2 locked=on state=floating layer=bottom
bspc rule -a Inkscape state=fullscreen
 